apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: tubesync
    namespace: tubesync
spec:
    interval: 15m
    chart:
        spec:
            chart: tubesync
            version: 8.11.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: tubesync
    values:
        global:
            stopAll: false
        TZ: America/Los_Angeles
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            gluetun:
                enabled: true
                # excludedNetworks_IPv4:
                #     - "192.168.0.0/24"
                # excludedNetworks_IPv6: []
                container:
                    env:
                        FIREWALL: "on"
                        FIREWALL_OUTBOUND_SUBNETS: "192.168.0.0/24"
                        VPN_SERVICE_PROVIDER: mullvad
                        VPN_TYPE: "wireguard"
                        WIREGUARD_PRIVATE_KEY: "${TUBESYNC_VPN_WG_PRIVATE_KEY}"
                        WIREGUARD_ADDRESSES: "${TUBESYNC_VPN_ADDRESS}"
                        SERVER_CITIES: "${TUBESYNC_VPN_CITIES}"
                        DNS_ADDRESS: 1.1.1.1
        autodiscovery:
            enabled: true
        credentials:
            tubesync:
                name: tubesync
                type: s3
                url: ${VOLSYNC_S3_URL}
                bucket: ${VOLSYNC_S3_BUCKET}
                accessKey: ${VOLSYNC_S3_ACCESSKEY}
                secretKey: ${VOLSYNC_S3_SECRETKEY}
                encrKey: ${VOLSYNC_S3_ENCKEY}
        persistence:
            config:
                volsync:
                    - credentials: tubesync
                      dest:
                        enabled: false
                      name: cfg
                      src:
                        enabled: true
                      type: restic
                mountPath: /config
            thumbnails:
                enabled: true
                type: nfs
                mountPath: /config/media/thumbs
                path: /mnt/PoolTwo/data/media/youtube/thumbnails/
                server: ${MEDIA_LOCAL_NAS_IP}
            downloads:
                enabled: true
                type: nfs
                mountPath: /downloads
                path: /mnt/PoolTwo/data/media/youtube/
                server: ${MEDIA_LOCAL_NAS_IP}
        release_name: tubesync
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsUser: 0
                hostNetwork: false
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                sharedKey: custom-shared-key
                loadBalancerIP: "${SERVICES_IP}"
                ports:
                    main:
                        port: 4848
                        targetPort: 4848
                type: LoadBalancer
        updated: true
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                DATABASE_CONNECTION: ""
                                http_PASS: ""
                                http_USER: ""
                                TUBESYNC_DEBUG: "False"
                                TUBESYNC_HOSTS: ""
                                TUBESYNC_WORKERS: "1"
                                YOUTUBE_DL_SKIP_UNAVAILABLE_FORMAT: "TRUE"
                                VIDEO_HEIGHT_UPGRADE: "TRUE"
                replicas: 1
                type: Deployment
        ingress:
          main:
            enabled: true
            primary: true
            ingressClassName: external
            integrations:
              traefik:
                  enabled: false
            annotations:
              nginx.ingress.kubernetes.io/auth-method: 'GET'
              nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local:9091/api/verify'
              nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN_0}?rm=$request_method'
              nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
            hosts:
                - host: tube.${DOMAIN_0}
                  paths:
                    - path: /
                      pathType: Prefix
