---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-anubis
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: ingress-anubis
    namespace: jaredallard-helmcharts
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicaCount: 2
      config:
        ANUBIS_VERSION: "1.19.1"
        WRAPPED_INGRESS_CLASS_NAME: "external"
        # Example usage:
        # prometheus.io/scrape:true,prometheus.io/scrape:false
        ANNOTATIONS: |
          metallb.io/ip-allocated-from-pool: main
          metallb.io/loadBalancerIPs: 192.168.0.225
