---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-anubis
  namespace: ingress-anubis
spec:
  interval: 15m
  chart: 
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
          stopAll: true
    image:
      repository: ghcr.io/jaredallard/ingress-anubis
      pullPolicy: IfNotPresent
      tag: 1.9.0@sha256:4a5913e4b0415afc98cc53b9ccb65f5a176ff81934ef6f4ad448616471d04309
    config:
        ANUBIS_VERSION: "1.19.1"
        WRAPPED_INGRESS_CLASS_NAME: "external"
        # Example usage:
        # prometheus.io/scrape:true,prometheus.io/scrape:false
        ANNOTATIONS: |
          metallb.io/ip-allocated-from-pool: main
          metallb.io/loadBalancerIPs: 192.168.0.225
    service:
      main:
        ports:
          main:
            port: 6885
    controller:
      ingressClassResource:
        name: anubis
        default: false
        controllerValue: k8s.io/external
      
