---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-anubis
  namespace: ingress-anubis
spec:
  interval: 15m
  chart: 
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/jaredallard/ingress-anubis
      pullPolicy: IfNotPresent
      tag: 1.6.1@sha256:c27a2d55ad2c13c6a3739428953b422429c4d89abacd0439666cbff216ec33ca
    config:
        ANUBIS_VERSION: "1.19.1"
        WRAPPED_INGRESS_CLASS_NAME: "external"
        # Example usage:
        # prometheus.io/scrape:true,prometheus.io/scrape:false
        ANNOTATIONS: |
          metallb.io/ip-allocated-from-pool: main
          metallb.io/loadBalancerIPs: 192.168.0.225
    # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # Automatically mount a ServiceAccount's API credentials?
      automount: true
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""
    service:
      main:
        ports:
          main:
            port: 6885
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    controller:
      ingressClassResource:
        name: anubis
        default: false
        controllerValue: k8s.io/external
      
