apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 15m
    chart:
        spec:
            chart: authentik
            version: 31.0.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: authentik
    values:
        TZ: America/Los_Angeles
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
        credentials:
            authentik:
                name: authentik
                type: s3
                url: ${VOLSYNC_S3_URL}
                bucket: ${VOLSYNC_S3_BUCKET}
                accessKey: ${VOLSYNC_S3_ACCESSKEY}
                secretKey: ${VOLSYNC_S3_SECRETKEY}
                encrKey: ${VOLSYNC_S3_ENCKEY}
        ingress:
          main:
            enabled: true
            hosts:
              - host: auth.${DOMAIN_0}
              - host: '*.${DOMAIN_0}'
                paths:
                  - path: /outpost.goauthentik.io
                    pathType: Prefix
            # integrations:
            #   traefik:
            #     enabled: true
            #     middlewares:
            #     - name: local
            #       namespace: traefik
            #   certManager:
            #     enabled: true
            #     certificateIssuer: ${CERT_ISSUER}
        persistence:
          media:
            enabled: true
            volsync:
                - credentials: authentik
                  dest:
                    enabled: true
                  name: geoip
                  src:
                    enabled: true
                  type: restic
            targetSelector:
              main:
                main:
                  mountPath: /media
              worker:
                worker:
                  mountPath: /media
          templates:
            enabled: true
            volsync:
                - credentials: authentik
                  dest:
                    enabled: true
                  name: geoip
                  src:
                    enabled: true
                  type: restic
            targetSelector:
              main:
                main:
                  mountPath: /templates
              worker:
                worker:
                  mountPath: /templates
          blueprints:
            enabled: true
            volsync:
                - credentials: authentik
                  dest:
                    enabled: true
                  name: geoip
                  src:
                    enabled: true
                  type: restic
            targetSelector:
              worker:
                worker:
                  # This will automatically change to `/blueprints`
                  # if `overwriteDefaultBlueprints` is set to `true
                  # Otherwise it will respect the value specified here
                  mountPath: /blueprints/custom
          certs:
            enabled: true
            volsync:
                - credentials: authentik
                  dest:
                    enabled: true
                  name: geoip
                  src:
                    enabled: true
                  type: restic
            mountPath: /certs
            targetSelector:
              worker:
                worker:
                  mountPath: /certs
          geoip:
            enabled: true
            volsync:
                - credentials: authentik
                  dest:
                    enabled: true
                  name: geoip
                  src:
                    enabled: true
                  type: restic
            targetSelector:
              main:
                main:
                  mountPath: /geoip
              worker:
                worker:
                  mountPath: /geoip
              geoip:
                geoip:
                  mountPath: /usr/share/GeoIP
        cnpg:
          main:
            # mode: recovery
            backups:
              enabled: true
            #   revision: "1"
              credentials: authentik
            recovery:
            #   revision: "x"
              credentials: authentik
            enabled: true
            user: authentik
            database: authentik
        release_name: authentik
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: ${MEDIA_GROUP}
                runAsUser: ${MEDIA_USER}
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                sharedKey: custom-shared-key
                loadBalancerIP: "${SERVICES_IP}"
                ports:
                    main:
                      protocol: https
                      port: 10229
                type: LoadBalancer
            # Server HTTP
            http:
              enabled: true
              type: ClusterIP
              ports:
                http:
                  enabled: true
                  protocol: http
                  port: 10230
            # Proxy
            proxy:
              enabled: true
              targetSelector: proxy
              ports:
                http:
                  enabled: true
                  protocol: http
                  port: 10227
                  targetSelector: proxy
                https:
                  enabled: true
                  protocol: https
                  port: 10228
                  targetSelector: proxy
            # Radius
            radius:
              enabled: true
              targetSelector: radius
              ports:
                radius:
                  enabled: true
                  protocol: udp
                  targetSelector: radius
                  port: 1812
            # LDAP
            ldap:
              enabled: true
              targetSelector: ldap
              ports:
                ldap:
                  enabled: true
                  port: 389
                  targetSelector: ldap
            # LDAPS
            ldaps:
              enabled: true
              targetSelector: ldap
              ports:
                ldaps:
                  enabled: true
                  port: 636
                  targetSelector: ldap