    worker:
    patches:
        - '@./patches/worker.yaml'
        # - '@./patches/enable_user-namespaces.yaml'
    # - hostname: k8s-control-2
    #   ipAddress: ${MASTER2IP_IP}
    #   controlPlane: true
    #   nameservers:
    #     - 192.168.0.253
    #     - 192.168.0.254
    #   installDiskSelector:
    #     size: <= 1600GB
    #   networkInterfaces:
    #     # suffix is the adapter mac adres.
    #     - interface: eth0
    #       addresses:
    #         - ${MASTER1IP_CIDR}
    #       routes:
    #         - network: 0.0.0.0/0
    #           gateway: ${GATEWAY}
    #       vip:
    #         ip: ${VIP}

    # - hostname: k8s-gpuworker-1
    #   ipAddress: ${GPUWORKERIP}
    #   nameservers:
    #     - 192.168.0.253
    #     - 192.168.0.254
    #   installDiskSelector:
    #     size: <= 250GB
    #   schematic:
    #       customization:
    #           systemExtensions:
    #               officialExtensions:
    #                   - siderolabs/amd-ucode
    #                   - siderolabs/nonfree-kmods-nvidia-production
    #                   - siderolabs/iscsi-tools
    #                   - siderolabs/util-linux-tools
        # - hostname: k8s-worker-dell-1
    #   ipAddress: ${WORKER1IP}
    #   nameservers:
    #     - 192.168.0.253
    #     - 192.168.0.254
    #   installDiskSelector:
    #     size: <= 250GB
    #   schematic:
    #       customization:
    #           systemExtensions:
    #               officialExtensions:
    #                   - siderolabs/amd-ucode
    #                   - siderolabs/iscsi-tools
    #                   - siderolabs/util-linux-tools
    # - hostname: k8s-worker-dell-2
    #   ipAddress: ${WORKER2IP}
    #   nameservers:
    #     - 1.1.1.1
    #     - 1.0.0.1
    #   installDiskSelector:
    #     size: <= 250GB
    #   schematic:
    #       customization:
    #           systemExtensions:
    #               officialExtensions:
    #                   - siderolabs/amd-ucode
    #                   - siderolabs/iscsi-tools
    #                   - siderolabs/util-linux-tools