apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: minecraft-server
    namespace: minecraft-server
spec:
    interval: 15m
    chart:
        spec:
            chart: minecraft-java
            version: 22.23.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: minecraft-server
    values:
        TZ: America/Los_Angeles
        addons:
            codeserver:
                enabled: false
                service:
                  type: "LoadBalancer"
                  loadBalancerIP: "${SERVER_IP}"
                  ports:
                    codeserver:
                      port: 12321
                ingress:
                  enabled: true
                  hosts:
                    - host: mc.cs.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                  integrations:
                    traefik:
                      enabled: true
                      entrypoints:
                        - web
                        - websecure
                      middlewares:
                        - name: auth
                          namespace: traefik
                    certManager:
                      enabled: true
                  certificateIssuer: ${CERT_ISSUER}   
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            minecraft-server:
                name: minecraft-server
                type: s3
                url: ${VOLSYNC_S3_URL}
                bucket: ${VOLSYNC_S3_BUCKET}
                accessKey: ${VOLSYNC_S3_ACCESSKEY}
                secretKey: ${VOLSYNC_S3_SECRETKEY}
                encrKey: ${VOLSYNC_S3_ENCKEY}
        persistence:
            data:
                enabled: true
                targetSelector:
                    main:
                        main:
                            mountPath: /data
                volsync:
                    - credentials: minecraft-server
                      dest:
                        enabled: true
                      name: cfg
                      src:
                        enabled: true
                      type: restic
            backups:
                enabled: true
                type: nfs
                mountPath: /backups
                path: /mnt/PoolTwo/data/servers/minecraft-backups/
                server: ${MEDIA_LOCAL_NAS_IP}
        release_name: minecraft-server
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                privileged: false
                readOnlyRootFilesystem: true
                runAsGroup: 1000
                runAsUser: 1000
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                sharedKey: custom-shared-key
                type: LoadBalancer
                loadBalancerIP: "${SERVER_IP}"
                ports:
                    main:
                        port: 25565
            # dashboard:
            #     enabled: true
            #     type: LoadBalancer
            #     loadBalancerIP: "${SERVER_IP}"
            #     ports:
            #       dashboard:
            #         enabled: true
            #         protocol: tcp
            #         port: 7867
        ingress:
          main:
            enabled: false
          # dashboard:
          #   enabled: true
          #   primary: true
          #   targetSelector:
          #     dashboard: dashboard
          #   hosts:
          #     - host: mc.${DOMAIN_0}
          #   integrations:
          #     traefik:
          #       enabled: true
        workload:
         main:
           podSpec:
             containers:
               main:
                 env:
                  OVERRIDE_SERVER_PROPERTIES: true
                  TYPE: "SPIGOT"
                  SPIGOT_DOWNLOAD_URL: "https://api.purpurmc.org/v2/purpur/1.21.4/2411/download"
                  VERSION: "1.21.4"
                  MOTD: "Welcome to TrainCraft"
