apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: minecraft-server
    namespace: minecraft-server
spec:
    interval: 15m
    chart:
        spec:
            chart: minecraft-java
            version: 22.34.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: minecraft-server
    values:
        global:
            stopAll: true
        TZ: America/Los_Angeles
        addons:
            codeserver:
                enabled: false
                service:
                  type: "LoadBalancer"
                  loadBalancerIP: "${SERVER_IP}"
                  ports:
                    codeserver:
                      port: 12321
                ingress:
                  enabled: false
                  ingressClassName: internal
                  hosts:
                    - host: mccs.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            minecraft-server:
                name: minecraft-server
                type: s3
                url: ${VOLSYNC_S3_URL}
                bucket: ${VOLSYNC_S3_BUCKET}
                accessKey: ${VOLSYNC_S3_ACCESSKEY}
                secretKey: ${VOLSYNC_S3_SECRETKEY}
                encrKey: ${VOLSYNC_S3_ENCKEY}
        persistence:
            data:
                enabled: true
                mountPath: /data
                type: nfs
                path: /mnt/PoolTwo/data/servers/minecraft/data
                server: ${MEDIA_LOCAL_NAS_IP}
                # volsync:
                #     - credentials: minecraft-server
                #       dest:
                #         enabled: false
                #       name: cfg
                #       src:
                #         enabled: true
                #       type: restic
            backups:
                enabled: true
                type: nfs
                mountPath: /backups
                path: /mnt/PoolTwo/data/servers/minecraft-backups/
                server: ${MEDIA_LOCAL_NAS_IP}
        release_name: minecraft-server
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                privileged: false
                readOnlyRootFilesystem: true
                runAsGroup: 1000
                runAsUser: 1000
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                sharedKey: custom-shared-key
                type: LoadBalancer
                loadBalancerIP: "${SERVER_IP}"
                ports:
                    main:
                        port: 25565
            dashboard:
                enabled: true
                type: LoadBalancer
                loadBalancerIP: "${SERVER_IP}"
                ports:
                  dashboard:
                    enabled: true
                    protocol: tcp
                    port: 7867
        ingress:
          main:
            enabled: false
          dashboard:
            enabled: true
            primary: true
            targetSelector:
              dashboard: dashboard
            hosts:
              - host: mc.${DOMAIN_0}
            integrations:
              traefik:
                enabled: false
        workload:
         main:
           podSpec:
             containers:
               main:
                 resources:
                  limits:
                    memory: 8Gi
                  requests:
                    memory: 6Gi
                 env:
                  DEBUG: false
                  MEMORY: 6G
                  ENABLE_WHITELIST: true
                  OPS: "thetraindoctor"
                  WHITELIST: "thetraindoctor,g4ort,2cd9c853-dd5d-4aa6-9fca-58efbe807863"
                  EXISTING_OPS_FILE: SYNCHRONIZE
                  OVERRIDE_SERVER_PROPERTIES: true
                  EXISTING_WHITELIST_FILE: SYNCHRONIZE
                  TYPE: "FORGE"
                  # MODPACK: /data/pack-zip/kustals-revenge-mods-1.0.0.zip
                  # GENERIC_PACKS_SUFFIX: .zip
                  # SKIP_GENERIC_PACK_UPDATE_CHECK: true
                  # CUSTOM_SERVER: "https://github.com/IzzelAliz/Arclight/releases/download/Trials%2F1.0.6/arclight-forge-1.20.1-1.0.6.jar"
                  # MODPACK_PLATFORM: "MODRINTH"
                  # MODRINTH_DOWNLOAD_DEPENDENCIES: required
                  # MODRINTH_MODPACK: https://modrinth.com/modpack/create-plus-with-sinytra/version/1.0.0
                  # MODRINTH_MODPACK: ""
                  # MODRINTH_PROJECTS: https://modrinth.com/modpack/kutsals-revenge
                  # MODRINTH_VERSION: ib3H7Lrj
                  VERSION: "1.20.1"
                  MOTD: "Welcome to TrainCraft"
