apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - cloudflareddns/ks.yaml
  - flaresolverr/ks.yaml
  - generic-device-plugin/ks.yaml
  - jellyfin/ks.yaml
  - jellyseerr/ks.yaml
  - lidarr/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent-v2/ks.yaml
  - radarr/ks.yaml
  - readarr/ks.yaml
  - sonarr/ks.yaml
  - steam-headless/ks.yaml
  - syncthing/ks.yaml
  - ubiquiti/ks.yaml
  - proxmox-dashboard/ks.yaml
  - truenas-dashboard/ks.yaml
  - pc-dashboard/ks.yaml
  - pc-kvm/ks.yaml
  - bazarr/ks.yaml
  - tubesync/ks.yaml
  - vaultwarden/ks.yaml
  - prox-kvm/ks.yaml
