apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
  namespace: generic-device-plugin
spec:
  interval: 15m
  chart:
    spec:
      chart: generic-device-plugin
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    workload:
        main:
          replicas: 3
          type: Deployment
  releaseName: generic-device-plugin