apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vWZwcpt33wU5PqpmYHz8fRqf58EF74U+/y72UW7D+Ur/7H4vEFfZXIFW5dz9w9J8lSgEj9Wkr9U26zaKclITl8qPY5e7H4aps/CLg1YgSSK217uaUJTxM8Xh+ljUKQxMjEfOnwbBou6JhRdeadqbwEJMbwwsDg/MeIsGrmNISi0Ff2HvQIdRuHLFt9xc+G+q/nuZ6f638UTrqV/ceKhnOGZ7X4hsvfB6Wcc73tuU8vz5q/Idr/NFLOlQofTEhT4d8zXuZni4a+MLUTelPaArMw5XyVBcZpmt2GM9OAbVyBTpn+mtQvbfn8Kg/FXTZegib4hpQeGGSjWUDUKUjE8ZEo69RRdUppGn/7hA9GCoGlcBfwpgQnGE9SocoiKjjXxe,iv:sLnTPhXsXNEC0PI4C5xVUiRXB+d/gDa1jef7qLhhbCA=,tag:iiOZsgCsE+huJYyELcFMCg==,type:str]
    identity.pub: ENC[AES256_GCM,data:w5y0pjtwF6V5gIiVUPx6jdVufWSmXSJ6VNiIjIM3SlJrYa5HfurkULq4UgKg40ONuFfRhiqfZ1GCMIjAiK+FB/6d1E2hPnB5lzKvHaOulrahRQaaV4jDpkcJsfkmSasAerAUqJPxnwyE912PNMMgGvmQVrzXp3VmmDwG84vRUd8AOYFEVsAzMLIvMBuaASD0E6hjDxjDzlUkWkEgN2mdovz8NRBq4HPd+CaMRRa8IYlnQy6pUXG1+QvR5A0H1ae9sHTYLN8Rs6s8QvgYSw==,iv:uQ7lofDHI7Qw18C72wl/v5bdT/Kob25yejoYdjTWAtk=,tag:cjDrSIY7xAt8Klb8QifROw==,type:str]
    known_hosts: ENC[AES256_GCM,data:wlY9b1NggYhUS6RYcSJ8Y9InrAqC4YnBWHHiSCZoCh5GC8QZ4dYkKG2ykKAOjZvrek/qI1ru56Sk+d6vFVO5NAik/1W0iOetWpnrKF2c0TUpm61mGy0c8G5PjMRbD5gfgRP58UzX0mqy7QQQJ/w4DIC5RCApAH8VjFbLxy/HPN9UUx298l/2wN1q9lGVxqtJO9jHiBCF0hItCWz18bqwCzWDdibr6yR3n0Jq,iv:xFWKhzivzwOFqsGy3+j4U6aKgSitc5tHAxyDYqi3iZw=,tag:U68eaAmOPps1piiqFDaDDQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1grv49vt8y6u7vse4030mgnfylx6c2jw7hlwhqs34nc9n9rpdwefqnr7vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWjEzVDhWQU5PaFBrQkpq
            TmpkY29rSnRXOTgvaDkzYS92TUFVZ21iMlgwCjlCUzhJNWhzZnQ0N3VNV2dFa0Nx
            RDlXNGFMT1RNRzlYUXdjZ2I3MktpTzAKLS0tIGZKQ1pNYmJlV3UvcVNnMWRjeGUv
            aDJPamxTYUxvNXhrc3pLclRaSFpsaUEKzMdD1NUXvbzp3hZ9w8r5JQlLnffl5FUJ
            ObQ4q30DPO5KzkQnRKGV3iud/8e7puqmXVqAcLqoeu//MW5T7R/5qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T03:45:54Z"
    mac: ENC[AES256_GCM,data:7G2dErA4o3nMnrPj8Diaq63nYey0CeNfHTMHEwVv7u4dc+L+FE6+0WbuJ3MRxtUv0BGskoLOabVXAs55uw6NxetQBYLevdu7irDghe25aOvAapYaeadk5Td7RsaH3A5CSqgoksyhxIwITBL50TE/SCdLSuVhyrlXbNwnFj766Zc=,iv:E4ffrXRP/H8P+bnkrnaR+sX/NSISOS8zZ+IYIDvPPZ0=,tag:f+u0y09qI5OvIFKaipasXw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
