apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0vVbtk9cRvkXNz7U+Jhr+FoTkxYLYVmrncdURkOT410db9L0y1vTVKEa0fmIbqLU2BQUbGiz+Ai3Y30CIIUmNIz1abJjuzY7+nZiHsvN3wneGc6XL4FSt/C/aeYOSeFPgtUeB+wOOuwxPwUcYCYo7PxdPRylrSvOmalJc4z4WBm7uQvPEJFMjqA4iRkaDeK9cwdOmskLV9xsIwHMfw0VuAxFHAv2dfCCi16B3Y+MNUWPHFg5hu9CTBNVjpHplAIM/t99wJuEhsz7qnf14WygEjw5j1x1+nrfXUwHKrygVi5cWhI0nvpO+8+V7g4IJZkaoK9zghKOTqX4G/jTuvwqROGieuHAR+pQBUavtqOEflBrledbbOfZvvr9klwwzaTX,iv:qhFsyTJz9msAvPC5wJzUKTmbIhVu7X2svmx1MB0uEps=,tag:dFOZMl1HMYvwmgRs2RB8DQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:BXM9RRLjPQhUPd0xjvn/2Pac2xz05peOvh4okvN2+9vyxstaErWnKcKJVH4MKrrv3qggcR+MNZ1WRinfX1AqJHGMRpmBQFLJfOgDLcVA8TSwgvpH4I5fuww1m5MT1fSkal9Vc0stf4S4eVZ1X5Q9KLsdfofuBfyZdhIDLcGrlwtwdTNl48AL9qI1rUruiuC6AmlpdemnC0k6pNQ6/TuaorlJzYtmUs9OEI1HXRSo9OwlCzSh/guM+GljtniP9C25z+yzMsJ/GY4GtfieSA==,iv:ZGYK+ko/dHtYx54BR7jj2EoknYio3jzyvG4IDOxane8=,tag:P/9BOo3qJBR3Elpg8klrWw==,type:str]
    known_hosts: ENC[AES256_GCM,data:T9fC4kqzjXfAFRlko+YWmzrowarz4Znz5RnwsYOWpArAfItJcVaOPpH2WozDyDwYSm8KIS5n9ST58LvcoLhQBuJyxcfzU1l17YOaXSjvS6PwZMi2YL8P9z8v4ff22twwcdxqYv0W9otWTdy43Lhihy/5dz19by+6Kp+6THbem641lTF83Lv5RMm8YxkBEOP0e7DESwVoiqIQOHFhybexXnksANycdtpyZZZh,iv:AYGxmftBl3FOyiwyyogUFngYU7wXeJ3Ca83GKZF+/cw=,tag:6HuJ5abQZtcjeDn/l/2TFA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1grv49vt8y6u7vse4030mgnfylx6c2jw7hlwhqs34nc9n9rpdwefqnr7vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdTZ0SDFrbWswS0N3YW1R
            Qzg3RU9XRkNab0pwUkdNL0ErR3dLY3I4blJvClY1TTJiM0NRT3NTZUlUTm9LWWt0
            bGM0TDNQU1BRK3FYNWh3UCtUUGQzakkKLS0tIC9HamZXNFdTVWIxUDJxZmdUZ0NM
            NXNvaC9ESHJYemlZeElBcFIyVzdtODQKI7xQ3pyOUfqAPLOZryIl2+Q+TQxf5krb
            YzHEImM0fBNE8QIif9LREIK1OUfXEkp2qG0eut32Lc3UdlgwhMR6PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T23:15:43Z"
    mac: ENC[AES256_GCM,data:gmW5eeMbGxlU0Z+5DRchssrSFA2RuLIdtvUzvCs4814XgYbGEl1VEm6ho+EyuiCCeFAZ1rKunq9gk78ibmu5FdbBAPDNmAStWyaX7K4RA36wFwh1f531ymbnSpT0rdtc9pX+s062K7h1F8C1yaooL3afoJcrQMcQ/AeRlAaPb0Q=,iv:8rY5sA1wi4MESAJLbciXwV7QLF1ssEOFR86+awWrwk4=,tag:zY5z7/KKak2lBA8lljd2Mg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
