apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:099xV0wVdFIjHC6n69jOXjznV+t0XiqE38FXW+2+YNbGNQraNCzDtOYI7l/HtIJFojExaSLmku2dp43c+pq+lsMmHDpaRPer5TMP54DZxfiIlPxJnL0N2jKLcCP18e4V7TOGRY1D6pxlbEZUl2Dy7t+gcpDzZMzsv4Te/YRwMEmKv3tjtOkmX6MZIEd1yfCqu1BJWBuyZz+nHOxNrjMQhUQRSEZHvDKXza/LcfMbd/jTBA+xUNxCSqW+13+fYS7rjtLL1jMH6eQ2m/jNXnyMOxmRJkNHDrh0hsq81GuWYVIAv12FkW1zoR+lh5o/CDZsJxhBIypMTb4Tk1MAGOf5zA0mNSGu3lJaF+gwSdOM1pgKA4xfvwfFlnVE+GNAm8Le,iv:RO6DR9gSJdNXTTW3offlcFJIMipawX4dGG/xp7DVf+0=,tag:UKcyMWfA9J7JgjTPNKHfVQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:TLl5weNi4Hzm6D5+D+jauE5faEEHMO8JTpZQkfcvZ9vsXzg868ZRTO4Zm1OUZakjWPCpXa8lVEiWoYwkx8+OqiVIOHqc9n6pxGuGD/LuLT6qxU96ezl+CWwVeRLpvMG2wpclz5meVz7RW35BnMD3jUgDBcL+0Jh0jbWW620W7w/9nhcmPIEqQvPlVw7jc0MKYITDbLRBhrC68SGk6c1fggE8VIyVfTJtHf2h1OzyhQ7VJ7gjXQuEo7lHFAtX3R0x4SDd/Mz8aLLNHP5fvw==,iv:TY1TH60lNTQ88/5mowEPX+T0iyHwGXcB7iCUCyOQ5js=,tag:uRmR8VxrXj1LMueqKOZOiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Nbrp6/0f3BE6rzUGpFH4qNtocF/9xaH7a5wZHSE134LwXrrmxBVm/fCsRhf1xtslBFeiXoP4uZdys3U6yrkMwyPg618OBREnDn5fr+Cycn63s7ezdjZJEnl+Ay1ORgaAJQUXkTbdzFBYMptAx4LUxdTcjRS0rUPlfjNNsX5mj6fingu1tr2ueMqsJQ9pe6srGiitPRMGhZw982gkmxl1huMI17zcuMs4zqbU,iv:OHinGBGdRQG1Cl365wqwFNqiOOePFH9hkZu/M3hYMlU=,tag:2PL8F9GIhbK8GzN6MI0ywA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1grv49vt8y6u7vse4030mgnfylx6c2jw7hlwhqs34nc9n9rpdwefqnr7vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCelZoY2U2ZkZobjlINHZE
            bjZERFBTZ0xxNmpIRkgvWXRuZTVlZ3JjbjNrCjB0MDVMQXViNXpmOE1KTWtjK2NG
            anFXNE5Pc0pySmx5Qk1FNDJTelN0YUEKLS0tIEFtSzk1OWhYZmJQRXRQQ3hEYTcz
            WnhybXJ6bVdhbUkyaUJwRC9MamYxTEEK05M3IlGAztKiR6ObtSSdtVcFThKQxaaR
            GiuH9Sn7Ci7cpVv56b6twrxHNLwlRRDqphKk8/6qJwZPOGYRIUBzdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T03:18:14Z"
    mac: ENC[AES256_GCM,data:xRnc9e+bnD0TOm/2+xM53n9bCQQJvKC+IyBXLJMlcyW3EYVJL5x8DB0R0KOaHiAilWPdBbvT/hf08heRtqnfWtH/y2MzmhSjwnZ2TLAaejbxghLUzw6pwW6fPg4ww5enRVBjrz+5h+MA7FwUTzhJ/uc6zs/tEDWoqLAEnDdvaYY=,iv:IC92sXCu1FYC+4dx0Tk9DHpLRqTOjCGF6O5ZZJvk3Ws=,tag:Z80ewJLLc2nDFmfAQrSufQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
