---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ingress-anubis
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/jaredallard/ingress-anubis
  ref:
    branch: master
  # secretRef:
  #   name: deploy-key
  ignore: |
    # exclude all
    /*
    # # include flux directories
    # !/repositories
