---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.4.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## set stopAll to "true" if you do not want to use traefik
    # and/or disable its service
    global:
      stopAll: false
    defaultCertificate: "domain-0-wildcard"
    service:
      main:
        type: ClusterIP
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          web:
            enabled: true
            port: 80
            protocol: http
            redirectTo: websecure
          websecure:
            enabled: true
            port: 443
            protocol: https
    middlewares:
      forwardAuth:
        - name: auth
          address: https://authentik-authentik.authentik.svc.cluster.local.svc.cluster.local:10229/outpost.goauthentik.io/auth/traefik
          authResponseHeaders:
          - authorization
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
          tls:
            insecureSkipVerify: false
          trustForwardHeader: true
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
              - web
              - websecure
            # middlewares:
            #   - name: forward-auth
            #     namespace: traefik
            # fixedMiddlewares:
            #   - name: chain-basic
            #     namespace: traefik
        hosts:
          - host: traefik.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
